spring.application.name=ClandeStock Backend

# Puerto del backend dentro del contenedor
server.port=${SERVER_PORT:8080}

# Datasource (usa variables de entorno; host "db" en Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Desactiva el log de SQL
spring.jpa.show-sql=false
# spring.jpa.show-sql=true

# Zona horaria
spring.jackson.time-zone=America/Argentina/Buenos_Aires
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires

# Health (Actuator)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# JWT (puedes mantener en properties por ahora; mejor migrarlo a variables de entorno más adelante)
application.security.jwt.secret-key=9f3a7c2d8b6e4a1f0c9d7e3b5a2f8c4d1e6b9a7c3f2d5e8b1c4a9d7f0e3b6c2a
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration-refresh=604800000


# Baja el nivel de log de Hibernate
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
